import { useEffect, useState } from 'react'
import { portfolio } from './data/portfolio'
import { Header } from './components/Header'
import { Icon } from './components/Icon'
import { ProjectModal } from './components/ProjectModal'
import { ContactForm } from './components/ContactForm'
import { Section } from './components/Section'
import profileImage from './assets/profile.jpg'
import './App.css'

const navigation = [['home', 'Home'], ['about', 'About'], ['skills', 'Skills'], ['projects', 'Projects'], ['contact', 'Contact']]

function App() {
  const [active, setActive] = useState('home')
  const [project, setProject] = useState(null)
  const [filter, setFilter] = useState('All')
  const [scrolled, setScrolled] = useState(false)
  const [progress, setProgress] = useState(0)
  const categories = ['All', ...new Set(portfolio.projects.map((item) => item.category))]
  const projects = filter === 'All' ? portfolio.projects : portfolio.projects.filter((item) => item.category === filter)
  useEffect(() => { const update = () => { setScrolled(window.scrollY > 16); const max = document.documentElement.scrollHeight - window.innerHeight; setProgress(max > 0 ? (window.scrollY / max) * 100 : 0) }; update(); window.addEventListener('scroll', update, { passive: true }); return () => window.removeEventListener('scroll', update) }, [])
  useEffect(() => { const observer = new IntersectionObserver((entries) => { const current = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (current) setActive(current.target.id) }, { rootMargin: '-35% 0px -55% 0px', threshold: [0, .2, .7] }); navigation.forEach(([id]) => { const node = document.getElementById(id); if (node) observer.observe(node) }); return () => observer.disconnect() }, [])
  return <><a className="skip-link" href="#main">Skip to content</a><div className="scroll-progress" style={{ transform: `scaleX(${progress / 100})` }} /><Header navigation={navigation} active={active} scrolled={scrolled} name={portfolio.profile.shortName} /><main id="main">
    <section id="home" className="hero section-shell"><div className="hero-copy reveal"><p className="eyebrow"><span /> Available for thoughtful collaboration</p><h1>{portfolio.profile.name}<br /><em>{portfolio.profile.role}</em></h1><p className="hero-description">{portfolio.profile.description}</p><div className="hero-actions"><a className="button button-primary" href="#projects">View my work <Icon name="arrow" /></a><a className="button button-secondary" href="#contact">Let&apos;s talk <Icon name="arrow" /></a></div><div className="social-row" aria-label="Social links">{portfolio.socials.map((social) => <a key={social.label} href={social.url} aria-label={social.label} target="_blank" rel="noreferrer"><Icon name={social.icon} /><span>{social.label}</span></a>)}</div></div><div className="hero-visual reveal" aria-hidden="true"><div className="orb orb-one" /><div className="orb orb-two" /><div className="code-window"><div className="window-top"><i /><i /><i /><span>building.tomorrow</span></div><pre><code><b>const</b> craft = {'{'}<br />  intention: <strong>&apos;always&apos;</strong>,<br />  details: <strong>&apos;matter&apos;</strong>,<br />  impact: <strong>&apos;meaningful&apos;</strong><br />{'}'}</code></pre><div className="window-status"><span>●</span> ready to create</div></div><div className="floating-chip chip-a">React</div><div className="floating-chip chip-b">Creative dev</div></div></section>
    <Section id="about" eyebrow="01 / About" title="Built with intent, shaped by curiosity."><div className="about-grid"><div className="profile-frame"><img src={profileImage} alt={`Portrait of ${portfolio.profile.name}`} /></div><div className="about-copy"><p className="lead">{portfolio.profile.about}</p><p>{portfolio.profile.approach}</p><dl className="focus-list">{portfolio.profile.focus.map((item, index) => <div key={item}><dt>0{index + 1}</dt><dd>{item}</dd></div>)}</dl></div></div></Section>
    <Section id="skills" eyebrow="02 / Expertise" title="A considered technical toolkit."><div className="skills-grid">{portfolio.skills.map((group) => <article className="skill-group" key={group.title}><div className="skill-group-icon"><Icon name={group.icon} /></div><h3>{group.title}</h3><div className="skill-tags">{group.items.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></Section>
    <Section id="services" eyebrow="03 / What I do" title="From direction to a polished digital experience."><div className="services-grid">{portfolio.services.map((service, index) => <article className="service" key={service.title}><span className="service-number">0{index + 1}</span><Icon name={service.icon} /><h3>{service.title}</h3><p>{service.description}</p></article>)}</div></Section>
    <Section id="projects" eyebrow="04 / Selected work" title="Work worth exploring."><div className="project-toolbar"><p>Kumpulan proyek akan ditampilkan setelah karya dan dokumentasi yang relevan ditambahkan.</p><div className="filters" aria-label="Filter projects">{categories.map((category) => <button className={filter === category ? 'active' : ''} onClick={() => setFilter(category)} key={category}>{category}</button>)}</div></div>{projects.length ? <div className="projects-grid">{projects.map((item) => <article className="project-card" key={item.name}><div className="project-image"><img src={item.image} alt="" loading="lazy" /><span>{item.category}</span></div><div className="project-content"><h3>{item.name}</h3><p>{item.summary}</p><div>{item.stack.map((tech) => <small key={tech}>{tech}</small>)}</div><button className="text-button" onClick={() => setProject(item)}>View details <Icon name="arrow" /></button></div></article>)}</div> : <div className="empty-state"><Icon name="folder" /><h3>Your projects will live here.</h3><p>Add real project entries to <code>src/data/portfolio.js</code> to activate the portfolio grid and filters.</p></div>}</Section>
    <Section id="credentials" eyebrow="05 / Credentials" title="Learning backed by proof."><div className="certificate-intro"><p>Selected certifications and technology credentials.</p><span>Verified record</span></div><div className="credential-archive"><div className="archive-copy"><p className="eyebrow">Google Drive archive</p><h3>{portfolio.credentialArchive.title}</h3><p>{portfolio.credentialArchive.description}</p><a className="button button-primary" href={portfolio.credentialArchive.url} target="_blank" rel="noreferrer">Open certificate folder <Icon name="arrow" /></a><small>Hosted securely in Google Drive</small></div><div className="drive-frame"><iframe title="Certificate archive in Google Drive" src={portfolio.credentialArchive.embedUrl} loading="lazy" allowFullScreen /></div></div>{portfolio.certificates.length ? <div className="certificates-grid">{portfolio.certificates.map((certificate) => <article className="certificate-card" key={certificate.title}><div className="certificate-image"><img src={certificate.image} alt={`Certificate: ${certificate.title}`} loading="lazy" /></div><div><p className="eyebrow">{certificate.issuer} / {certificate.issued}</p><h3>{certificate.title}</h3>{certificate.credentialUrl && <a className="text-button" href={certificate.credentialUrl} target="_blank" rel="noreferrer">Verify credential <Icon name="arrow" /></a>}</div></article>)}</div> : null}</Section>
    <Section id="contact" eyebrow="06 / Contact" title="Have a thoughtful idea? Let&apos;s make it real."><div className="contact-grid"><div><p className="lead">{portfolio.contact.intro}</p><a className="contact-email" href={`mailto:${portfolio.contact.email}`}>{portfolio.contact.email} <Icon name="arrow" /></a><p className="contact-note">Alamat email ini telah ditautkan sebagai kanal komunikasi profesional.</p></div><ContactForm email={portfolio.contact.email} /></div></Section>
  </main><footer><div><a className="footer-mark" href="#home">{portfolio.profile.shortName}<span>.</span></a><p>{portfolio.profile.footer}</p></div><nav aria-label="Footer navigation">{navigation.slice(0, -1).map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</nav><div className="footer-bottom"><span>© {new Date().getFullYear()} {portfolio.profile.name}</span><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>Back to top <Icon name="arrow-up" /></button></div></footer><ProjectModal project={project} onClose={() => setProject(null)} /></>
}
export default App
